# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT fleetingram.wsgi

beta_settings:
    cloud_sql_instances: conexe:us-central1:fleetingramcore

runtime_config:
  python_version: 3
# [END runtime]